package CalcApp;


/**
* CalcApp/CalcInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcInterface.idl
* Tuesday, November 17, 2015 9:23:03 PM CET
*/

abstract public class CalcInterfaceHelper
{
  private static String  _id = "IDL:CalcApp/CalcInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, CalcApp.CalcInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static CalcApp.CalcInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CalcApp.CalcInterfaceHelper.id (), "CalcInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static CalcApp.CalcInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalcInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, CalcApp.CalcInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static CalcApp.CalcInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalcApp.CalcInterface)
      return (CalcApp.CalcInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalcApp._CalcInterfaceStub stub = new CalcApp._CalcInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static CalcApp.CalcInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof CalcApp.CalcInterface)
      return (CalcApp.CalcInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CalcApp._CalcInterfaceStub stub = new CalcApp._CalcInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
