package CalcApp;


/**
* CalcApp/CalcInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalcInterface.idl
* Tuesday, November 17, 2015 9:23:03 PM CET
*/

public interface CalcInterfaceOperations 
{
  String add (double x, double y);
  String subtract (double a, double b);
  String multiply (double x, double y);
  String divide (double a, double b);
  String random ();
  void shutdown ();
} // interface CalcInterfaceOperations
